version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SECRET_KEY=base64
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=takanakuq
      - DB_USER=psqlUser
      - DB_PASSWORD=passPGSQL
    networks:
      - takanakuq-net
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:  
    image: postgres:16.2
    environment:
      - POSTGRES_USER=psqlUser
      - POSTGRES_PASSWORD=passPGSQL
    networks:
      - takanakuq-net
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/takanakuq.sql:/docker-entrypoint-initdb.d/takanakuq.sql

networks:
  takanakuq-net: