version: '3.9'
services:
  app:
    build: .
    environment:
      - SECRET_KEY=base64
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=luchadores
      - DB_USER=psqlUser
      - DB_PASSWORD=passPGSQL
    networks:
      - luchadores-net
    depends_on:
      - db
  
  db:  
    image: postgres:16.2
    environment:
      - POSTGRES_USER=psqlUser
      - POSTGRES_PASSWORD=passPGSQL
    networks:
      - luchadores-net
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres/luchadores.sql:/docker-entrypoint-initdb.d/luchadores.sql

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - luchadores-net
    depends_on:
      - app

volumes:
  postgres-data:

networks:
  luchadores-net: