version: '3.9'
services:
  app:
    build: .
    environment:
      - SECRET_KEY=base64

      - AWS_REGION=
      - AWS_ACCESS_KEY=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_BUCKET_NAME=

      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=takanakuq
      - DB_USER=
      - DB_PASSWORD=

    networks:
      - takanakuq-net
    depends_on:
      - db
  
  db:  
    image: postgres:16.2
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    networks:
      - takanakuq-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres/takanakuq.sql:/docker-entrypoint-initdb.d/takanakuq.sql

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - takanakuq-net
    depends_on:
      - app

volumes:
  postgres-data:

networks:
  takanakuq-net: